name: "PR Integration Tests"

on:
  pull_request_target: {}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  integ-test:
    if: github.repository_owner == 'awslabs'
    uses: ./.github/workflows/reusable_integ-tests.yml
    with:
      ref: ${{ github.ref }}